Feature: User Login # features/login.feature:1
  As a user
  I want to login to the application
  So that I can access my account
  Feature: User Login  # features/login.feature:1

  @smoke @login
  Scenario: Successful login with valid credentials                  # features/login.feature:10
    Given I am on the login page                                     # features/steps/login_steps.py:5
      Traceback (most recent call last):
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\model.py", line 1991, in run
          match.run(runner.context)
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\matchers.py", line 105, in run
          self.func(context, *args, **kwargs)
        File "features\steps\login_steps.py", line 7, in step_navigate_to_login
          context.login_page = LoginPage(context.driver)
                                         ^^^^^^^^^^^^^^
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\runner.py", line 430, in __getattr__
          raise AttributeError(msg)
      AttributeError: 'Context' object has no attribute 'driver'

    When I login with username "testuser" and password "password123" # None
    Then I should be redirected to the home page                     # None
    And I should see the welcome message                             # None

  @negative @login
  Scenario: Login with invalid credentials                        # features/login.feature:16
    Given I am on the login page                                  # features/steps/login_steps.py:5
      Traceback (most recent call last):
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\model.py", line 1991, in run
          match.run(runner.context)
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\matchers.py", line 105, in run
          self.func(context, *args, **kwargs)
        File "features\steps\login_steps.py", line 7, in step_navigate_to_login
          context.login_page = LoginPage(context.driver)
                                         ^^^^^^^^^^^^^^
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\runner.py", line 430, in __getattr__
          raise AttributeError(msg)
      AttributeError: 'Context' object has no attribute 'driver'

    When I login with username "invalid" and password "wrongpass" # None
    Then I should see the error message                           # None
    And the error message should contain "invalid credentials"    # None

  @negative @login
  Scenario: Login with empty username               # features/login.feature:22
    Given I am on the login page                    # features/steps/login_steps.py:5
      Traceback (most recent call last):
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\model.py", line 1991, in run
          match.run(runner.context)
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\matchers.py", line 105, in run
          self.func(context, *args, **kwargs)
        File "features\steps\login_steps.py", line 7, in step_navigate_to_login
          context.login_page = LoginPage(context.driver)
                                         ^^^^^^^^^^^^^^
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\runner.py", line 430, in __getattr__
          raise AttributeError(msg)
      AttributeError: 'Context' object has no attribute 'driver'

    When I enter username ""                        # None
    And I enter password "password123"              # None
    And I click the login button                    # None
    Then I should see the error message             # None
    And the error message should contain "username" # None

  @negative @login
  Scenario: Login with empty password               # features/login.feature:30
    Given I am on the login page                    # features/steps/login_steps.py:5
      Traceback (most recent call last):
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\model.py", line 1991, in run
          match.run(runner.context)
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\matchers.py", line 105, in run
          self.func(context, *args, **kwargs)
        File "features\steps\login_steps.py", line 7, in step_navigate_to_login
          context.login_page = LoginPage(context.driver)
                                         ^^^^^^^^^^^^^^
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\runner.py", line 430, in __getattr__
          raise AttributeError(msg)
      AttributeError: 'Context' object has no attribute 'driver'

    When I enter username "testuser"                # None
    And I enter password ""                         # None
    And I click the login button                    # None
    Then I should see the error message             # None
    And the error message should contain "password" # None

  @login
  Scenario Outline: Login with different invalid credentials -- @1.1   # features/login.feature:44
    Given I am on the login page                                       # features/steps/login_steps.py:5
      Traceback (most recent call last):
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\model.py", line 1991, in run
          match.run(runner.context)
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\matchers.py", line 105, in run
          self.func(context, *args, **kwargs)
        File "features\steps\login_steps.py", line 7, in step_navigate_to_login
          context.login_page = LoginPage(context.driver)
                                         ^^^^^^^^^^^^^^
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\runner.py", line 430, in __getattr__
          raise AttributeError(msg)
      AttributeError: 'Context' object has no attribute 'driver'

    When I login with username "invalid" and password "pass123"        # None
    Then I should see the error message                                # None

  @login
  Scenario Outline: Login with different invalid credentials -- @1.2   # features/login.feature:45
    Given I am on the login page                                       # features/steps/login_steps.py:5
      Traceback (most recent call last):
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\model.py", line 1991, in run
          match.run(runner.context)
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\matchers.py", line 105, in run
          self.func(context, *args, **kwargs)
        File "features\steps\login_steps.py", line 7, in step_navigate_to_login
          context.login_page = LoginPage(context.driver)
                                         ^^^^^^^^^^^^^^
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\runner.py", line 430, in __getattr__
          raise AttributeError(msg)
      AttributeError: 'Context' object has no attribute 'driver'

    When I login with username "user123" and password "wrongpass"      # None
    Then I should see the error message                                # None

  @login
  Scenario Outline: Login with different invalid credentials -- @1.3   # features/login.feature:46
    Given I am on the login page                                       # features/steps/login_steps.py:5
      Traceback (most recent call last):
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\model.py", line 1991, in run
          match.run(runner.context)
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\matchers.py", line 105, in run
          self.func(context, *args, **kwargs)
        File "features\steps\login_steps.py", line 7, in step_navigate_to_login
          context.login_page = LoginPage(context.driver)
                                         ^^^^^^^^^^^^^^
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\runner.py", line 430, in __getattr__
          raise AttributeError(msg)
      AttributeError: 'Context' object has no attribute 'driver'

    When I login with username "testuser" and password "wrongpass"     # None
    Then I should see the error message                                # None

  @login
  Scenario Outline: Login with different invalid credentials -- @1.4   # features/login.feature:47
    Given I am on the login page                                       # features/steps/login_steps.py:5
      Traceback (most recent call last):
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\model.py", line 1991, in run
          match.run(runner.context)
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\matchers.py", line 105, in run
          self.func(context, *args, **kwargs)
        File "features\steps\login_steps.py", line 7, in step_navigate_to_login
          context.login_page = LoginPage(context.driver)
                                         ^^^^^^^^^^^^^^
        File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\runner.py", line 430, in __getattr__
          raise AttributeError(msg)
      AttributeError: 'Context' object has no attribute 'driver'

    When I login with username "wronguser" and password "password123"  # None
    Then I should see the error message                                # None

